#!/bin/sh

#qsub -v var1=../McManus/constitutive_regions.bed,var2=dm3,var3=droSec1,var4=../mel_sec_data/Hyb_r1.dm3.mosaik.bed.converted,var5=../mel_sec_data/Hyb_r2.dm3.mosaik.bed.converted,var6=../mel_sec_data/Hyb_r1.droSec1.mosaik.bed.lifted.converted,var7=../mel_sec_data/Hyb_r2.droSec1.mosaik.bed.lifted.converted,var8=../mel_sec_data/Hyb.mosaik.readout.txt,var9=../mel_sec_data/Hyb.mosaik.exonout.txt,var10=../mel_sec_data/Hyb.mosaik.geneout.txt classify.csh

#qsub -v var1=../McManus/constitutive_regions.bed,var2=dm3,var3=droSec1,var4=../mel_sec_data/Mix_r1.dm3.mosaik.bed.converted,var5=../mel_sec_data/Mix_r2.dm3.mosaik.bed.converted,var6=../mel_sec_data/Mix_r1.droSec1.mosaik.bed.lifted.converted,var7=../mel_sec_data/Mix_r2.droSec1.mosaik.bed.lifted.converted,var8=../mel_sec_data/Mix.mosaik.readout.txt,var9=../mel_sec_data/Mix.mosaik.exonout.txt,var10=../mel_sec_data/Mix.mosaik.geneout.txt classify.csh

#runon perl classify.0.5.pl ../McManus/const_exons.dm3.bed dm3 droSec1 ../mel_sec_data/Hyb_r1.dm3.mosaik.bed.converted ../mel_sec_data/Hyb_r2.dm3.mosaik.bed.converted ../mel_sec_data/Hyb_r1.droSec1.mosaik.bed.lifted.converted ../mel_sec_data/Hyb_r2.droSec1.mosaik.bed.lifted.converted ../mel_sec_data/Hyb.mosaik.readout.txt ../mel_sec_data/Hyb.mosaik.exonout.txt ../mel_sec_data/Hyb.mosaik.geneout.txt &

#runon perl classify.0.5.pl ../McManus/const_exons.dm3.bed dm3 droSec1 ../mel_sec_data/Mix_r1.dm3.mosaik.bed.converted ../mel_sec_data/Mix_r2.dm3.mosaik.bed.converted ../mel_sec_data/Mix_r1.droSec1.mosaik.bed.lifted.converted ../mel_sec_data/Mix_r2.droSec1.mosaik.bed.lifted.converted ../mel_sec_data/Mix.mosaik.readout.txt ../mel_sec_data/Mix.mosaik.exonout.txt ../mel_sec_data/Mix.mosaik.geneout.txt &

#qsub -v var1=../McManus/constitutive_regions.bed,var2=dm3,var3=droSec1,var4=../mel_sec_data/mRNA-Seq/dm3/dm3.mate1.dm3.mosaik.bed.converted,var5=../mel_sec_data/mRNA-Seq/dm3/dm3.mate2.dm3.mosaik.bed.converted,var6=../mel_sec_data/mRNA-Seq/dm3/dm3.mate1.droSec1.mosaik.bed.lifted.converted,var7=../mel_sec_data/mRNA-Seq/dm3/dm3.mate2.droSec1.mosaik.bed.lifted.converted,var8=../mel_sec_data/mRNA-Seq/dm3/dm3.mosaik.reads.txt,var9=../mel_sec_data/mRNA-Seq/dm3/dm3.mosaik.exons.txt,var10=../mel_sec_data/mRNA-Seq/dm3/dm3.mosaik.genes.txt classify.csh

#qsub -v var1=../McManus/constitutive_regions.bed,var2=dm3,var3=droSec1,var4=../mel_sec_data/mRNA-Seq/droSec1/droSec1.mate1.dm3.mosaik.bed.converted,var5=../mel_sec_data/mRNA-Seq/droSec1/droSec1.mate2.dm3.mosaik.bed.converted,var6=../mel_sec_data/mRNA-Seq/droSec1/droSec1.mate1.droSec1.mosaik.bed.lifted.converted,var7=../mel_sec_data/mRNA-Seq/droSec1/droSec1.mate2.droSec1.mosaik.bed.lifted.converted,var8=../mel_sec_data/mRNA-Seq/droSec1/droSec1.mosaik.reads.txt,var9=../mel_sec_data/mRNA-Seq/droSec1/droSec1.mosaik.exons.txt,var10=../mel_sec_data/mRNA-Seq/droSec1/droSec1.mosaik.genes.txt classify.csh

#perl classify.0.5.pl ../McManus/constitutive_regions.bed dm3 droSec1 ../mel_sec_data/mRNA-Seq/dm3/dm3.mate1.dm3.mosaik.bed.converted ../mel_sec_data/mRNA-Seq/dm3/dm3.mate2.dm3.mosaik.bed.converted ../mel_sec_data/mRNA-Seq/dm3/dm3.mate1.droSec1.mosaik.bed.lifted.converted ../mel_sec_data/mRNA-Seq/dm3/dm3.mate2.droSec1.mosaik.bed.lifted.converted ../mel_sec_data/mRNA-Seq/dm3/dm3.mosaik.reads.txt ../mel_sec_data/mRNA-Seq/dm3/dm3.mosaik.exons.txt ../mel_sec_data/mRNA-Seq/dm3/dm3.mosaik.genes.txt &

#perl classify.0.5.pl ../McManus/constitutive_regions.bed dm3 droSec1 ../mel_sec_data/mRNA-Seq/droSec1/droSec1.mate1.dm3.mosaik.bed.converted, ../mel_sec_data/mRNA-Seq/droSec1/droSec1.mate2.dm3.mosaik.bed.converted ../mel_sec_data/mRNA-Seq/droSec1/droSec1.mate1.droSec1.mosaik.bed.lifted.converted ../mel_sec_data/mRNA-Seq/droSec1/droSec1.mate2.droSec1.mosaik.bed.lifted.converted ../mel_sec_data/mRNA-Seq/droSec1/droSec1.mosaik.reads.txt ../mel_sec_data/mRNA-Seq/droSec1/droSec1.mosaik.exons.txt ../mel_sec_data/mRNA-Seq/droSec1/droSec1.mosaik.genes.txt &
