#tsimbazaza
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazaza/tsimbazaza.mate1.tsimbazaza.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazaza/tsimbazaza.mate1.tsimbazaza.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazaza/tsimbazaza.mate2.tsimbazaza.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazaza/tsimbazaza.mate2.tsimbazaza.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazaza/tsimbazaza.mate1.droSec1.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazaza/tsimbazaza.mate1.droSec1.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazaza/tsimbazaza.mate2.droSec1.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazaza/tsimbazaza.mate2.droSec1.mosaik.bed.lifted.converted &

#droSec1
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/droSec1/droSec1.mate1.tsimbazaza.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/droSec1/droSec1.mate1.tsimbazaza.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/droSec1/droSec1.mate2.tsimbazaza.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/droSec1/droSec1.mate2.tsimbazaza.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/droSec1/droSec1.mate1.droSec1.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/droSec1/droSec1.mate1.droSec1.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/droSec1/droSec1.mate2.droSec1.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/droSec1/droSec1.mate2.droSec1.mosaik.bed.lifted.converted &

#tsimbazaza+droSec1
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazaza+droSec1/tsimbazaza+droSec1.mate1.droSec1.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazaza+droSec1/tsimbazaza+droSec1.mate1.droSec1.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazaza+droSec1/tsimbazaza+droSec1.mate2.droSec1.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazaza+droSec1/tsimbazaza+droSec1.mate2.droSec1.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazaza+droSec1/tsimbazaza+droSec1.mate1.tsimbazaza.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazaza+droSec1/tsimbazaza+droSec1.mate1.tsimbazaza.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazaza+droSec1/tsimbazaza+droSec1.mate2.tsimbazaza.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazaza+droSec1/tsimbazaza+droSec1.mate2.tsimbazaza.mosaik.bed.lifted.converted &

#tsimbazazaXdroSec1
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazazaXdroSec1/tsimbazazaXdroSec1.mate1.droSec1.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazazaXdroSec1/tsimbazazaXdroSec1.mate1.droSec1.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazazaXdroSec1/tsimbazazaXdroSec1.mate2.droSec1.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazazaXdroSec1/tsimbazazaXdroSec1.mate2.droSec1.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazazaXdroSec1/tsimbazazaXdroSec1.mate1.tsimbazaza.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazazaXdroSec1/tsimbazazaXdroSec1.mate1.tsimbazaza.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/tsimbazazaXdroSec1/tsimbazazaXdroSec1.mate2.tsimbazaza.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/tsimbazazaXdroSec1/tsimbazazaXdroSec1.mate2.tsimbazaza.mosaik.bed.lifted.converted &

#droSec1Xtsimbazaza
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/droSec1Xtsimbazaza/droSec1Xtsimbazaza.mate1.droSec1.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/droSec1Xtsimbazaza/droSec1Xtsimbazaza.mate1.droSec1.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/droSec1Xtsimbazaza/droSec1Xtsimbazaza.mate2.droSec1.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/droSec1Xtsimbazaza/droSec1Xtsimbazaza.mate2.droSec1.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/droSec1Xtsimbazaza/droSec1Xtsimbazaza.mate1.tsimbazaza.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/droSec1Xtsimbazaza/droSec1Xtsimbazaza.mate1.tsimbazaza.mosaik.bed.lifted.converted &
runon perl ../perlScripts/convertChr2Gene.0.2.pl ../sim_sec_data/mRNA-Seq/droSec1Xtsimbazaza/droSec1Xtsimbazaza.mate2.tsimbazaza.mosaik.bed.lifted ../sim_sec_data/Sim_sec_gaps_gt19.bed ../McManus/constitutive_regions.bed ../sim_sec_data/mRNA-Seq/droSec1Xtsimbazaza/droSec1Xtsimbazaza.mate2.tsimbazaza.mosaik.bed.lifted.converted &
